"""Squashed migration

Revision ID: 2f84d7ebd2f4
Revises: a19c67fd18e1
Create Date: 2025-05-21 11:23:28.635742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f84d7ebd2f4'
down_revision: Union[str, None] = 'a19c67fd18e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
