"""Squashed migration

Revision ID: a19c67fd18e1
Revises: 2e1d2b181311
Create Date: 2025-05-21 11:20:20.412201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19c67fd18e1'
down_revision: Union[str, None] = '2e1d2b181311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('for_action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'for_action')
    # ### end Alembic commands ###
