"""fix

Revision ID: bfd1a7b814f0
Revises: d688bf591bbb
Create Date: 2025-05-16 17:33:13.943736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd1a7b814f0'
down_revision: Union[str, None] = 'd688bf591bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notifications', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications', 'users', ['receiver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('notifications', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
