"""added price field to reapair request 

Revision ID: fda3e00a50b2
Revises: 71c17d12219c
Create Date: 2025-05-16 08:32:51.842136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda3e00a50b2'
down_revision: Union[str, None] = '71c17d12219c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_requests', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair_requests', 'price')
    # ### end Alembic commands ###
